// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAsY2HaRPZ5BLU2loK0ZvDeEXEjfE6MHgk',
    appId: '1:538772791305:web:f087a3ed0138dd9b4358d8',
    messagingSenderId: '538772791305',
    projectId: 'srmbus-23b92',
    authDomain: 'srmbus-23b92.firebaseapp.com',
    databaseURL: 'https://srmbus-23b92-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'srmbus-23b92.appspot.com',
    measurementId: 'G-SLB68SE1KS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBLPYGAu9pIGgA149aN5iWuN1SzeJbC89o',
    appId: '1:538772791305:android:f312ead0ffe599724358d8',
    messagingSenderId: '538772791305',
    projectId: 'srmbus-23b92',
    databaseURL: 'https://srmbus-23b92-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'srmbus-23b92.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD0mMh8G8l7iESF-ftKLLZPcNxRJOIjjU8',
    appId: '1:538772791305:ios:fcf4275de2aa290c4358d8',
    messagingSenderId: '538772791305',
    projectId: 'srmbus-23b92',
    databaseURL: 'https://srmbus-23b92-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'srmbus-23b92.appspot.com',
    iosClientId: '538772791305-ri3oltq68jc49hi40qg3g47raqe27qhg.apps.googleusercontent.com',
    iosBundleId: 'com.example.srmBus',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD0mMh8G8l7iESF-ftKLLZPcNxRJOIjjU8',
    appId: '1:538772791305:ios:fcf4275de2aa290c4358d8',
    messagingSenderId: '538772791305',
    projectId: 'srmbus-23b92',
    databaseURL: 'https://srmbus-23b92-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'srmbus-23b92.appspot.com',
    iosClientId: '538772791305-ri3oltq68jc49hi40qg3g47raqe27qhg.apps.googleusercontent.com',
    iosBundleId: 'com.example.srmBus',
  );
}
